### DISCUSSION TITLE
Are these requirements needed in my Console Project?

### DISCUSSION THREAD

**Discussion by john0isaac** [beeware/briefcase#1963] [Q&A] [answered]
I created a new project with the command `briefcase new` and it generated a pyproject.toml with these lines:

```toml
[tool.briefcase.app.hello-cli.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "23.08"
flatpak_sdk = "org.freedesktop.Sdk"
```

![image](https://github.com/user-attachments/assets/e809c8bd-ba5f-4141-8878-aca2d5216f44)

I was wondering are they actually needed? and if yes, why?

P.s, I tried removing them and everything seems to work fine on my macOS.
