### ISSUE TITLE
Remove `python-dateutil` error suppression for pytest once `>2.8.2` is released

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1428]
### Describe the bug

For Python 3.12, `python-dateutil` is currently causing CI to raise an error for using `datetime.utcfromtimestamp()`. A mitigation was put in place to suppress the error until a new release.

### Steps to reproduce

N/A

### Expected behavior

Remove the error suppression configuration from `pyproject.toml` once a release >2.8.2 is cut.

```toml
[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
    # suppress until python-dateutil>2.8.2 is released (https://github.com/dateutil/dateutil/issues/1284)
    "ignore:.*datetime.utcfromtimestamp\\(\\) is deprecated.*:DeprecationWarning:",
]
```

### Environment

N/A

### Additional context

RE: beeware/briefcase#1290
