### ISSUE TITLE
Add documentation for document type `extension` field

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1771]
### Describe the bug

When document types are configured for an app, the `extension` field is required but [not documented](https://briefcase.readthedocs.io/en/latest/reference/configuration.html#document-types).

For instance:
```toml
[tool.briefcase.app.podium.document_type.deck]
description = "Podium Slide Deck"
extension = "podium"
icon = "src/podium/resources/podium-deck"
url = 'https://beeware.org/project/projects/applications/podium/'
```

### Steps to reproduce

See #1770 for example of what happens when `extension` isn't configured.

### Expected behavior

The need and purpose of `extension` is documented.

The difference between this `extension` field and the extension specified in the name of the table isn't immediately clear...so, these differences may need to be understood to properly document this. Additionally, it's also possible one should be falling back to another in the code.

### Environment

- Operating System: Sonoma
- Python version: 3.12.2
- Software versions:
  - Briefcase: `0.3.18.dev279+gdbe11cf0`

### Logs

See #1770.
