### ISSUE TITLE
ModuleNotFoundError: pywintypes when running exe program

### ISSUE THREAD

**Issue by greghonoazos** [beeware/briefcase#2181]
### Describe the bug

When the build runs everything goes well. But when the program runs on Windows it gives this error

My project.toml

```toml
[project]
name = "payroll"
version = "0.1.0"
description = ""
authors = [
    {name = "Gregorio Honorato"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "pywin32 (>=308,<309)",
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pytest (>=8.3.4,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
flake8 = "^4.0.1"
black = "^21.12b0"
isort = "^5.10.1"

[tool.mypy]
disallow_incomplete_defs = "True"
disallow_untyped_defs = "True"
ignore_missing_imports = "True"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["src", "tests"]
testpaths = ["tests"]

[tool.pylint]
init-hook = "import sys; sys.path.append('./src'), sys.path.append('./tests')"
fail-under = "9.5"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.messages_control]
disable = ["C0114", "C0116", "C0301", "R0903", "W1203"]

[tool.pylint.similarities]
ignore-imports = "yes"
min-similarity-lines = "6"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.commitizen]
version = "ˆ2.32.5"
tag_format = "v$version"
version_files = [
  "pyproject.toml:version",
  "commitizen/__version__.py",
  ".pre-commit-config.yaml:rev:.+Commitizen"
]

[tool.poetry.scripts]
lint = "flake8"
format = "black . && isort ."

[tool.briefcase]
project_name = "Payroll"
bundle = "com.example"
version = "0.0.1"
url = ""
license.file = "LICENSE"
author = "Gregorio Honorato"
author_email = "greghono@gmail.com"

[tool.briefcase.app.src]
formal_name = "Payroll"
description = "App handler payment data"
long_description = """More details about the app should go here.
"""
sources = [
    "src",
]
test_sources = [
    "tests",
]
console_app = true

requires = [
    "requests (>=2.32.3,<3.0.0)",
    "pywin32 (==308)",    
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pytest (>=8.3.4,<9.0.0)"
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.src.linux.system.debian]
system_requires = [
    "requests (>=2.32.3,<3.0.0)",
    "pywin32 (==308)",    
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pytest (>=8.3.4,<9.0.0)"
]

system_runtime_requires = [
    "requests (>=2.32.3,<3.0.0)",
    "pywin32 (==308)",
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pytest (>=8.3.4,<9.0.0)"
]

[tool.briefcase.app.src.windows]
requires = [
    "requests (>=2.32.3,<3.0.0)",
    "pywin32 (==308)",
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pytest (>=8.3.4,<9.0.0)"
]
```

### Expected behavior

That runs in terminal mode

### Environment

- Operating System: Windows
- Python version: Python 3.12
- Software versions: 
  - Briefcase: 0.3.22
  - used requirements:
    - "pywin32 (==308)",
    - "pandas (>=2.2.3,<3.0.0)",
    - "python-dotenv (>=1.0.1,<2.0.0)",
    - "colorlog (>=6.9.0,<7.0.0)",
    - "pytest (>=8.3.4,<9.0.0)"
  - ...

### Logs

```

```
