### ISSUE TITLE
Add "version" command to briefcase

### ISSUE THREAD

**Issue by saroad2** [beeware/briefcase#360]
Taking inspiration from [poetry](https://python-poetry.org/docs/pyproject/), we should implement a "version" command for "briefcase". For example, given the following *pyproject.toml* file:

```toml
[tool.briefcase]
project_name = "EddingtonGUI"
bundle = "com.eddington_gui"
version = "0.0.2.dev0"
url = "https://eddington_gui.com/eddington_gui"
license = "Apache Software License"
author = 'Sagi Shadur'
author_email = "saroad2@gmail.com"
```

The command `briefcase version` should output "0.0.2.dev0"
