### ISSUE TITLE
Works in dev mode but not in run mode

### ISSUE THREAD

**Issue by RiccardoBarbieri** [beeware/briefcase#478]
**Describe the bug**
When I run 'briefcase dev' in vs code terminal with beeware venv active the app works just fine but when i run 'briefcase create', 'briefcase build' and 'briefcase run' on windows the terminal says Unable to start app animals

To reproduce I link here a github repo with the entire folder created by 'briefcase create', it is in animals sub-folder:
https://github.com/RiccardoBarbieri/beeware-projects

**Environment:**
 - Operating System: Windows
 - Python version: 3.8.1

**Comment by saroad2** [comment]
Hey!

When you run `briefcase dev` you run the app in your own virtual environment, but when you run `briefcase run` you run it in with an isolated *python* runner with only specific libraries.

In order to make it work, you should add the dependencies in your *pyproject.toml* file. that would probably solve the problem.

**Comment by RiccardoBarbieri** [comment]
> Hey!
> 
> When you run `briefcase dev` you run the app in your own virtual environment, but when you run `briefcase run` you run it in with an isolated _python_ runner with only specific libraries.
> 
> In order to make it work, you should add the dependencies in your _pyproject.toml_ file. that would probably solve the problem.

Hey @saroad2, thanks for you reply. 

So you're saying that I just have to add the dependencies (by dependencies you mean external libraries that I use in my code? In this specific case I use lxml and requests) but I have no clue on how to do it. I looked at the file and I don't really understand what's going on inside that .toml, could you set me in the right path?

**Comment by saroad2** [comment]
Sure. Here's your *pyproject.toml* file:

``` toml
[tool.briefcase.app.animals]
formal_name = "AnimalS"
description = "Search animals by specifing the first and last letter"
icon = "src/animals/resources/animals"
sources = ['src/animals']
requires = []  # <- Add dependencies here
```

If you want an example, you can take a look at my project [here](https://github.com/EddLabs/eddington-gui/blob/master/pyproject.toml).

I'm closing the issue for now. If this problem still occurring, please feel free to reopen the issue.
