### ISSUE TITLE
Allow excluding files and folders from the build

### ISSUE THREAD

**Issue by dominickj-tdi** [beeware/briefcase#550]
I'd like for there to be a way to exclude files and folders from the final application build. I have a number of files in the src folder which are only needed for development and not on clients actually running the application.

A simple `excludes` parameter in the pyproject.toml would be ideal. something like this:

```toml
[tool.briefcase.app.myapp]
formal_name = "My App"
description = "My App"
icon = "src/myapp/client/resources/client"
sources = ['src/myapp']
sources_exclude = [
    '*.ui',
    '*.xcf',
    '*.qrc',
    'src/myapp/server',
    'src/myapp/tests',
    '**/__pycache__']
```

I need to keep these files in the source tree for development, but packaging them up with the application doesn't really do any good, and just means extra data to send over the network and store on everyone's hard drives.

As an extra bonus, it would also be nice to have a minify option for all the Python source files as well, but that's a separate issue.
