### ISSUE TITLE
Pillow Related error when trying to execute appimage

### ISSUE THREAD

**Issue by daedalus-0** [beeware/briefcase#618]
Hi. Packaging my application works fine but when trying to run the produced appimage I get an error which I think is related to pillow because of the referenced library in the output. 

    Traceback (most recent call last):
      File "/tmp/.mount_qcomicOkkPRb/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/tmp/.mount_qcomicOkkPRb/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/.mount_qcomicOkkPRb/usr/app/qcomics/__main__.py", line 1, in <module>
        from qcomics.app import main
      File "/tmp/.mount_qcomicOkkPRb/usr/app/qcomics/app.py", line 9, in <module>
        from qcomics.reader import Reader
      File "/tmp/.mount_qcomicOkkPRb/usr/app/qcomics/reader.py", line 4, in <module>
        from PIL import Image
      File "/tmp/.mount_qcomicOkkPRb/usr/app_packages/PIL/Image.py", line 114, in <module>
        from . import _imaging as core
    ImportError: libtiff-102594ad.so.5.7.0: ELF load command address/offset not properly aligned

**Comment by freakboy3742** [comment]
Agreed this definitely looks like a PIL problem. 

Have you also included libtiff in the `system_requires` definition? If you haven't, it's possible the problem is that PIL is trying to access a library outside the app image.

**Comment by daedalus-0** [comment]
that was the issue, I missed one dependency, thanks a lot.

**Comment by gambhiro** [comment]
@daedalus-0 what did your `system_requires` list look like? I ran into the same issue, but `system_requires = ["libtiff-dev",]` didn't solve it.

**Comment by gambhiro** [comment]
For Linux I had to specify Pillow 7.2.0, the later versions produce the `libtiff ... offset not properly aligned` error when running the AppImage. I wonder what happened in Pillow that causes it.

Windows and MacOS works with Pillow 9.0.0.


``` toml
[tool.briefcase.app.helloapp.macOS]
requires = ["Pillow>=9.0.0"]

[tool.briefcase.app.helloapp.linux]
requires = ["Pillow==7.2.0"]
system_requires = ["libtiff-dev"]

[tool.briefcase.app.helloapp.windows]
requires = ["Pillow>=9.0.0"]

# And for Poetry:

[tool.poetry.dependencies]
Pillow = [
  { version = "7.2.0", platform = "linux"},
  { version = "^9.0.0", platform = "win32" },
  { version = "^9.0.0", platform = "darwin" },
]
```
